global:
  scrape_interval:     15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
rule_files:
scrape_configs:
  - job_name: 'prometheus-avalanche'
    static_configs:
    - targets: ['172.17.0.6:9001']
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']
      labels:
        instance: 'prom2'

#remote_write:
#  - url: "http://172.17.0.3:1234/receive"
