global:
  scrape_interval:     15s
  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets:
rule_files:
scrape_configs:
  - job_name: 'federate'
    scrape_interval: 15s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="prometheus"}'

    static_configs:
      - targets: ['172.17.0.6:9090']
        labels:
          instance: 'prom1'
      
      - targets: ['172.17.0.8:9090']
        labels:
          instance: 'prom2'


remote_write:
  - url: "http://172.17.0.3:1234/receive"
